apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: www-gulf-0
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "my-storage-class"
  resources:
    requests:
      storage: 80Gi