apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: dev
  name: gulf
spec:
  selector:
    matchLabels:
      app: web-gulf
  serviceName: gulf-dns
  replicas: 3
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: gulf-web
      spec:
        terminationGracePeriodSeconds: 10
        imagePullSecrets: 
        - name: dockerhub-credentials
        containers:
        - name: gulf-web
          image: dennar/gulf-web
          ports:
          - containerPort: 8080
            name: gulf 
          volumeMounts:
          - name: www
            mountPath: /var/www/html
  volumeClaimTemplates:
    - metadata:
        name: www
      spec: 
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "last-storage"
        resources:
          requests:
            storage: 20Gi