apiVersion: v1 
kind: PersistentVolume 
metadata:
  name: pv 
  namespace: dev
spec:
  capacity:
    storage: 100Gi
accessModes: 
- ReadWriteOnce
storageClassName: my-storage-class
hostPath:
  path: "/var/www/html"