apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: dev
  name: gulf
spec:
  selector:
    matchLabels:
      app: gulf-web
  strategy:
    type: RollingUpdate
    rollingUpdate:
<<<<<<< HEAD:statefulset.yml
      maxUnavailable: 2
      maxSurge: 4
=======
      maxUnavailable: 1
      maxSurge: 1
>>>>>>> master:kubernetes-configs/statefulset.yml
  serviceName: gulf-dns
  replicas: 3
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: gulf-web
    spec:
      terminationGracePeriodSeconds: 10
      imagePullSecrets: 
        - name: dockerhub-credentials
      containers:
        - name: gulf-web
          image: gcr.io/roar1984/gulf-web
          ports:
            - containerPort: 8080
              name: gulf 
          volumeMounts:
            - name: www
              mountPath: /var/www/html
  volumeClaimTemplates:
    - metadata:
        name: www
      spec: 
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "last-storage"
        resources:
          requests:
            storage: 20Gi

  initContainers:
    - name: gke-gcloud-auth
      image: google/cloud-sdk:latest
      command:
        - '/bin/sh'
        - '-c'
        - 'gke-gcloud-auth-plugin'