name: Skaffold Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker to use the gcloud command-line tool
        run: gcloud auth configure-docker

      - name: Build and deploy with Skaffold
        uses: hiberbee/github-action-skaffold@latest
        with:
            skaffold-version: 2.8.0
            kubectl-version: 1.25.0
            command: run