name: Deploy to GKE with Skaffold

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare service account key
        run: |
          echo -n "${{ secrets.GCP_SA_KEY }}" | base64 --decode > /tmp/gcp-key.json
          gcloud auth activate-service-account --key-file=/tmp/gcp-key.json

      - name: Configure Docker to use the gcloud command-line tool
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{secrets.GCP_PROJECT_ID}}/gulf-web:latest .
          docker push gcr.io/${{secrets.GCP_PROJECT_ID}}/gulf-web:latest

      - name: Set up Skaffold
        uses: hiberbee/github-action-skaffold@1.27.0
        with:
          skaffold-version: 1.38.0
          kubectl-version: 1.25.0

      - name: Deploy with Skaffold
        run: skaffold run -p ${{secrets.GCP_PROJECT_ID}}