name: Deploy to Google Cloud

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure Google Cloud CLI
        # Use tr to remove line breaks from Base64 encoded key
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | tr -d '\n' | base64 --decode > $HOME/gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-key.json
          gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
          gcloud config set project "${{ secrets.GCP_PROJECT_ID }}"

      - name: Build and Deploy with Skaffold
        run: |
          # Run Skaffold to build and deploy the application
          skaffold run

