name: Deploy to Google Cloud

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure Google Cloud CLI
        run: |
          echo ${{ secrets.GCP_SA_KEY }} | base64 --decode > ${HOME}/gcp-key.json
          docker run -v ${HOME}:/root -e GOOGLE_APPLICATION_CREDENTIALS=/root/gcp-key.json google/cloud-sdk gcloud auth activate-service-account --key-file=/root/gcp-key.json
          docker run -v ${HOME}:/root -e GOOGLE_APPLICATION_CREDENTIALS=/root/gcp-key.json google/cloud-sdk gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Build and Deploy with Skaffold
        run: |
          skaffold run
