name: Deploy to Google Cloud

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure Google Cloud CLI
        run: |
          # Decode and save the Google Cloud service account key
          echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > $HOME/gcp-key.json
          
          # Set the environment variable for Google Cloud authentication
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-key.json
          
          # Activate the service account using the key
          gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
          
          # Set the Google Cloud project ID
          gcloud config set project "${{ secrets.GCP_PROJECT_ID }}"

      - name: Build and Deploy with Skaffold
        run: |
          # Run Skaffold to build and deploy the application
          skaffold run
