name: Skaffold Deploy

on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Update Google Cloud SDK
        run: gcloud components update

      - name: Check Google Cloud SDK installation
        run: ls -l $(gcloud info --format='value(installation.sdk_root)')

      - name: Checkout Terraform repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.5

      - name: Initialize Terraform
        run: |
          terraform init

      - name: Plan Terraform changes
        run: |
          terraform plan -out=tfplan

      - name: Apply Terraform changes
        run: terraform apply -auto-approve tfplan

  deploy:
    runs-on: ubuntu-latest

    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate with Google Cloud
        run: gcloud auth configure-docker

      - name: Configure Kubernetes context
        run: gcloud container clusters get-credentials gulf-cluster --zone us-east4

      - name: Check Kubernetes context
        run: kubectl config current-context

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Skaffold
        uses: hiberbee/github-action-skaffold@latest
        with:
          skaffold-version: 2.8.0
          kubectl-version: 1.25.0

      - name: Set platform for Skaffold
        run: skaffold config set --kube-context=gulf-cluster local-cluster true

      - name: Build and deploy with Skaffold
        run: skaffold run --platform linux
