name: Deploy to GKE with Skaffold

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Verify gcloud authentication
        run: |
            gcloud auth list
            gcloud config list
        
        

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Skaffold
        uses: hiberbee/github-action-skaffold@1.27.0
        with:
          skaffold-version: 2.8.0
          kubectl-version: 1.25.0

      - name: Deploy with Skaffold
        run: skaffold run -p ${{secrets.GCP_PROJECT_ID}}