on:
    push:
      branches:
        - master
  
jobs:
    deploy:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
  
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
  
        - name: Prepare service account key
          run: |
            # Remove leading and trailing whitespaces
            secret_key="${{ secrets.GCP_SA_KEY }}"
            secret_key="${secret_key#"${secret_key%%[![:space:]]*}"}"
            secret_key="${secret_key%"${secret_key##*[![:space:]]}"}"
            
            # Decode the base64-encoded key and print it
            decoded_key=$(echo -n "$secret_key" | base64 -d -)
            echo "Decoded Key: $decoded_key"
            
            # Write the decoded key to a file
            echo -n "$decoded_key" > /tmp/gcp-key.json
            
            # Activate service account
            gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
        
        
        
          
        - name: Set project ID
          run: |
            gcloud config set project "***"
  
        - name: Build and Deploy with Skaffold
          run: |
            skaffold run
  