name: Skaffold Deploy

on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Initialize Terraform
        run: |
          cd path/to/terraform/files
          terraform init

      - name: Apply Terraform Changes
        run: |
          cd path/to/terraform/files
          terraform apply -auto-approve

  deploy:
    runs-on: ubuntu-latest

    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate with Google Cloud
        run: gcloud auth configure-docker

      - name: Configure Kubernetes context
        run: gcloud container clusters get-credentials YOUR_CLUSTER_NAME --zone YOUR_CLUSTER_ZONE

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Skaffold
        uses: hiberbee/github-action-skaffold@latest
        with:
          skaffold-version: 2.8.0
          kubectl-version: 1.25.0

      - name: Build and deploy with Skaffold
        run: skaffold run
